### ISSUE TITLE
Interest in information

### ISSUE THREAD

**Issue by sepp89117** [hypoxic/gopro-HERO7#2]
Hi, where do you get "YY%00%08%0d%00%01%01" ? My Hero5 black starts beeping when I send it via udp.

I'm working on a project to control multiple cameras at the same time. It works fine. See [GoPro-Multiple-Smart-Remote-ESP8266](https://github.com/sepp89117/GoPro-Multiple-Smart-Remote-ESP8266)

I was able to figure out some commands. Of course I'm interested in more. So how do you get the parameters of YY?
I look forward to your reply
Thanks

**Comment by hypoxic** [comment]
They're the internal GCCB / SDK / YY / i2c commands as they call them. This
guy has some of them documented.
https://orangkucing.github.io/Hero4_I2C_Commands.html#

**Comment by sepp89117** [comment]
Hey, thank you for this tip! The YY i2c commands also work over UDP.
Unfortunately, Orangkucing does not list the YY 0x0 0x8 commands and I had to figure it out myself in part.
Now I can also read out the battery level and the set date and time via my ESP8266 application.
Setting the date and time does not work yet. If I have time, I'll take care of it.
Many thanks!
